### ISSUE TITLE
Tokenizer is nil when running iOS 9.3

### ISSUE THREAD

**Issue by RubenKid** [eliot1019/AttrTextView#1]
First of all, congrats for the awesome class!. I am having an issue running it on iOS 9.3 because somehow tokenizer is nil and so, when clicking on the text is crashing the app. Any idea? Thanks!

**Comment by eliot1019** [comment]
Hi @RubenKid I'll take a look at this for iOS9 as it is a class I'm currently planning on using for production code and will push a fix sometime in the next two weeks. I'll let you know when I do!

**Comment by RubenKid** [comment]
Hi @eliot1019! I found the reason why my app was crashing and I was wrong, the issue is not that Tokenizer is null but seems that in iOS 9, if textView is not selectable, the library crashes trying to retrieve the clicked position. This behaviour doesn't happen on iOS 10 (just to let you know). I'll close the issue. Thanks!
